version: 0.2
env:
    secrets-manager:
      LOGIN: Raidproject/sonar:sonartoken
      HOST: Raidproject/sonar:host
      Organization: Raidproject/sonar:organization
      Project: Raidproject/sonar:Project
      
      build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=psaicharan000 -Dsonar.organization=psaicharan000 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Raidproject
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=psaicharan000 | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
artifacts:
    files:
      - '**/*'
