version: 0.2
env:
    secrets-manager:
      LOGIN: psaicharan000/sonar:sonartoken
      HOST: psaicharan000/sonar:host
      Organization: psaicharan000/sonar:organization
      Project: psaicharan000/sonar:Project
 
    build:
      commands:
        - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
        #mvn verify sonar:sonar -Dsonar.projectKey=$Project -Dsonar.organization=$Organization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$LOGIN
        #- mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$Project
        - sleep 5
        - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
        - cat result.json
        - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
#      - |- 
#        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project | jq -r '.projectStatus.status')
#        echo "SonarCloud analysistatus is $quality_status"; 
#        if [ $quality_status = "ERROR" ] ; then exit 1;fi
artifacts:
    files:
      - '**/*'
